name: pillag
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: IBM Plex Mono
      fonts:
        - asset: fonts/IBMPlexMono-Regular.ttf
        - asset: fonts/IBMPlexMono-Italic.ttf
          style: italic
        - asset: fonts/IBMPlexMono-Bold.ttf
          weight: 700
        - asset: fonts/IBMPlexMono-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/IBMPlexMono-ExtraLight.ttf
          weight: 200
        - asset: fonts/IBMPlexMono-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/IBMPlexMono-Light.ttf
          weight: 300
        - asset: fonts/IBMPlexMono-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: fonts/IBMPlexMono-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: fonts/IBMPlexMono-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/IBMPlexMono-Thin.ttf
          weight: 100
        - asset: fonts/IBMPlexMono-ThinItalic.ttf
          weight: 100
          style: italic


